name: HELICS Version Update

on: [repository_dispatch]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.action == 'helics-version-update'
    steps:
    - uses: actions/checkout@v2
    - name: Update the HELICS_VERSION file to ${{ github.event.client_payload.version }}
      run: echo "${{ github.event.client_payload.version }}" > HELICS_VERSION
    - name: Commit updated HELICS_VERSION file
      run: git add HELICS_VERSION && commit -m "Update HELICS version to ${{ github.event.client_payload.version }}"
    - name: Push updated HELICS_VERSION
      run: git push
