name: Update HELICS Packages

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Do a dry run of the update process, without making the commit'
        required: false
        type: boolean

jobs:
  update-helics-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read HELICS_VERSION
      id: hver
      run: echo "::set-output name=HELICS_VERSION::$(cat HELICS_VERSION)"
    - name: Print HELICS_VERSION
      run: echo "${{ steps.hver.outputs.HELICS_VERSION }}"
    - uses: GMLC-TDC/pyhelics/.github/workflows/update-helics.yml@main
      with:
        version: ${{ steps.hver.outputs.HELICS_VERSION }}
        dryrun: ${{ inputs.dryrun }}
    - name: Update pyhelics package
      env:
        GH_TOKEN: ${{ secrets.HELICS_PACKAGING_TOKEN }}
      run: |
        HELICS_VERSION="$(cat HELICS_VERSION)"
        gh workflow run --repo GMLC-TDC/pyhelics update-helics.yml -f dryrun=${{ inputs.dryrun }} -f version=${HELICS_VERSION}
    - name: Update matHELICS package
      env:
        GH_TOKEN: ${{ secrets.HELICS_PACKAGING_TOKEN }}
      run: |
        HELICS_VERSION="$(cat HELICS_VERSION)"
        gh workflow run --repo GMLC-TDC/matHELICS update-helics.yml -f dryrun=${{ inputs.dryrun }} -f version=${HELICS_VERSION}

