name: Update HELICS Packages

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Do a dry run of the update process, without making the commit'
        required: false
        type: boolean

jobs:
  get-helics-version:
    name: Get HELICS Version
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.hver.outputs.HELICS_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Read HELICS_VERSION
      id: hver
      run: echo "::set-output name=HELICS_VERSION::$(cat HELICS_VERSION)"

  update-spack:
    needs: get-helics-version
    uses: ./.github/workflows/update-spack-package.yml
    with:
      dryrun: ${{ inputs.dryrun }}
    secrets: inherit

  update-mingw:
    needs: get-helics-version
    uses: ./.github/workflows/update-mingw-package.yml
    with:
      dryrun: ${{ inputs.dryrun }}
    secrets: inherit

  update-language-bindings:
    name: Trigger Language Bindings Version Update
    runs-on: ubuntu-latest
    needs: get-helics-version
    steps:
    - name: Update pyhelics package
      env:
        GH_TOKEN: ${{ secrets.HELICS_PACKAGING_TOKEN }}
      run: gh workflow run --repo GMLC-TDC/pyhelics update-helics.yml -f dryrun=${{ inputs.dryrun }} -f version=${{ needs.get-helics-version.outputs.ver }}
    - name: Update matHELICS package
      env:
        GH_TOKEN: ${{ secrets.HELICS_PACKAGING_TOKEN }}
      run: gh workflow run --repo GMLC-TDC/matHELICS update-helics.yml -f dryrun=${{ inputs.dryrun }} -f version=${{ needs.get-helics-version.outputs.ver }}

