name: Update HELICS Packages

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Do a dry run of the update process, without making the commit'
        required: false
        type: boolean

jobs:
  get-helics-version:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.hver.outputs.HELICS_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Read HELICS_VERSION
      id: hver
      run: echo "::set-output name=HELICS_VERSION::$(cat HELICS_VERSION)"

  update-pyhelics:
    needs: get-helics-version
    uses: GMLC-TDC/pyhelics/.github/workflows/update-helics.yml@main
    with:
      version: ${{ needs.get-helics-version.outputs.ver }}
      dryrun: ${{ inputs.dryrun }}

  update-helics-version:
    runs-on: ubuntu-latest
    needs: get-helics-version
    steps:
    - uses: actions/checkout@v2
    - name: Print HELICS_VERSION
      run: echo "${{ needs.get-helics-version.outputs.ver }}"
    - name: Update pyhelics package
      env:
        GH_TOKEN: ${{ secrets.HELICS_PACKAGING_TOKEN }}
      run: |
        HELICS_VERSION="$(cat HELICS_VERSION)"
        gh workflow run --repo GMLC-TDC/pyhelics update-helics.yml -f dryrun=${{ inputs.dryrun }} -f version=${HELICS_VERSION}
    - name: Update matHELICS package
      env:
        GH_TOKEN: ${{ secrets.HELICS_PACKAGING_TOKEN }}
      run: |
        HELICS_VERSION="$(cat HELICS_VERSION)"
        gh workflow run --repo GMLC-TDC/matHELICS update-helics.yml -f dryrun=${{ inputs.dryrun }} -f version=${HELICS_VERSION}

